all:
  children:
    managers:
      hosts:
        swarm-manager:
    workers:
      hosts:
        swarm-worker:
        
  vars:
    ansible_user: jenkins
    ansible_ssh_private_key_file: '~/ansible_key'
    ansible_python_interpreter: "/usr/bin/python3"